# Generated by Django 2.2.3 on 2019-08-26 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='address',
        ),
    ]
