# Generated by Django 2.2.4 on 2019-09-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samapp', '0002_remove_author_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=50)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AddField(
            model_name='language',
            name='version',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
